### ISSUE TITLE
Add abilty to sumbit posts to subreddits

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/Baconit#12]
Basic, just needs to be done.

**Comment by mvaneerde** [comment]
Potential subfeatures:

1. Allow posting selftext posts with no text (/r/showerthoughts does this a lot)
2. Allow posting to a subreddit that is not subscribed to, either remotely or locally, e.g. if I found it via search or I typed it in manually
3. (Big feature) allow posting a local image as a link post via the file picker (e.g., submit it to imgur)

**Comment by QuinnDamerell** [comment]
Done in 4.2 except for the image upload.
