### ISSUE TITLE
Karma next to comment usernames is unclear

### ISSUE THREAD

**Issue by mike-eason** [QuinnDamerell/Baconit#25]
![image](https://cloud.githubusercontent.com/assets/7103013/11153513/643dca0a-8a31-11e5-935c-1d27aa4182b4.png)

On thread comments, the numbers beside the username represents karma. It took me a worryingly long time to work this out, and I had to check the thread on Reddit to see what the number actually meant.

It's not a huge problem, but it was unclear at first. Perhaps a different placement, or font colour could be what's needed here. or maybe even some kind of symbol to indicate that its karma?

**Comment by joeyfoo** [comment]
I'll suggest following the reddit convention: simply by appending with "points". 

Romans8389 **2149 points** 4 hours ago

**Comment by QuinnDamerell** [comment]
Good point, I have updated it :)
