### ISSUE TITLE
Updated privacy page

### ISSUE THREAD

**Issue by joeyfoo** [QuinnDamerell/Baconit#29]
I've made some changes to the style and the text of the privacy policy. 

A live example is hosted here: http://files.joeyfoo.com/media/privacy.html
The code and the diff is here, so you can see the diff with my changes: https://gist.github.com/joeyfoo/55c1488ae5fb163a1e1d

**Comment by QuinnDamerell** [comment]
AWESOME! I made that super quick at 10am in the morning Thursday because the store rejected Baconit without it. Your version looks so much better, thanks!

I have updated it. :)
