### ISSUE TITLE
Add User Page Support

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/Baconit#3]
Add user page support. 

Make search results link to them
Add a link to them from posts
Add a link to them from comments.

**Comment by paulbartrum** [comment]
I've added support for /u/user links in this commit: 76208a630a591b8448d397f0c4c1f8e07467e452

It needs Baconit support so the links actually do something when you click on them :-)

**Comment by QuinnDamerell** [comment]
I will do that, thanks :)
