### ISSUE TITLE
SubReddit and username in main listView should be clickable

### ISSUE THREAD

**Issue by ameno-** [QuinnDamerell/Baconit#33]
![image](https://cloud.githubusercontent.com/assets/2416135/11214497/9c722368-8d0f-11e5-989e-eef022046800.png)

**Comment by joeyfoo** [comment]
Not a bug. 

> I actually kind of did that on purpose. While it saved a few seconds for people who were pro users, it confused a lot of users who didn't know what was going on. There isn't enough UI context in the list to support the dual tap function. Perhaps it will come back later via an option.

https://www.reddit.com/r/baconit/comments/3so3nj/its_here_baconit_for_windows_10/cwzjgy4

**Comment by ameno-** [comment]
I see, I'll shut this down then. Thanks!
