### ISSUE TITLE
When in landscape (w/ start menu on the left), part of the UI covers the voting buttons

### ISSUE THREAD

**Issue by Humorousone** [QuinnDamerell/Baconit#34]
This is a minor graphical issue.

When in landscape mode, with the start menu on the left, the little bar from which you can open the options menu covers the voting buttons.

Trying to click the buttons opens up the options menu. 

screenshot
http://imgur.com/ifeR2L6

Lumia 640, Windows phone 8.1

**Comment by joeyfoo** [comment]
This is the git repository for the UWP version of Baconit which runs on Windows 10 devices. Bugs from the 8.1 version shouldn't be posted here.

**Comment by QuinnDamerell** [comment]
Yep, thanks. :)
