### ISSUE TITLE
It's possible to get into a state where comments no longer load.

### ISSUE THREAD

**Issue by haydenmc** [QuinnDamerell/Baconit#35]
After browsing on desktop for a few minutes on a couple of different occasions, I was able to get into a state where comments simply wouldn't load for posts. No particular repro steps. Scrolling down reveals some blank padding. This persists on every post.

![baconitbug](https://cloud.githubusercontent.com/assets/5422053/11285752/059a683e-8ec6-11e5-845d-c4a5fc977285.PNG)

![image](https://cloud.githubusercontent.com/assets/5422053/11285771/188c1078-8ec6-11e5-8989-baf23d3f21d7.png)

**Comment by QuinnDamerell** [comment]
I believe with recent updates this has been fixed. Let me know if you see it again.
