### ISSUE TITLE
Asterisks are appearing with an escape backslash in comments.

### ISSUE THREAD

**Issue by haydenmc** [QuinnDamerell/Baconit#36]
See [this comment](https://reddit.com/r/bestof/comments/3tf3m2/redditor_gives_a_good_explanation_on_why_windows/cx62ind):
![bug](https://cloud.githubusercontent.com/assets/5422053/11287107/13981582-8ece-11e5-913a-08619ba30916.PNG)

**Comment by paulbartrum** [comment]
This bug is fixed in the latest version of UniversalMarkdown.
