### ISSUE TITLE
Dropdowns for "lock screen" and "wallpaper" subreddits change width while you scroll, making it hard to use mouse/trackpad

### ISSUE THREAD

**Issue by mvaneerde** [QuinnDamerell/Baconit#37]
See http://i.imgur.com/EWofWIN.png or attached
![baconit-dropdown](https://cloud.githubusercontent.com/assets/14753320/11362511/ec11ce08-9248-11e5-8ebd-3e7e3fe79d4d.png)

Note the vertical scrollbar jumps horizontally

Ideally the width of the dropdown would be such that the longest subreddit just fit

This doesn't happen on Phone

**Comment by QuinnDamerell** [comment]
These should be set to a default size now, this shouldn't happen. :)
