### ISSUE TITLE
Backing out of an still-masked NSFW post briefly shows the post

### ISSUE THREAD

**Issue by mrwizard1000** [QuinnDamerell/Baconit#42]
If I open a link that is marked as NSFW, I get the NSFW warning correctly. If I hit the back button without clicking the "tap anywhere to view" the image will briefly be shown before the view window closes. It's quick enough that it's possible (although I haven't proven) that the image loaded behind the NSFW mask, and I wouldn't expect that to happen.

**Comment by QuinnDamerell** [comment]
This will be fixed in the next update. :)
