### ISSUE TITLE
Privacy Policy Typos

### ISSUE THREAD

**Issue by diogorolo** [QuinnDamerell/Baconit#50]
In http://baconit.quinndamerell.com/privacy.html I found two typos:

Currently is:
 * ..."exactly the same as your browser does when your on the reddit website"

Should be:
 * ..."exactly the same as your browser does when you're on the reddit website"

---

Currently is:
 * "We will never send reddit anything personal information"

Should be:
 * "We will never send reddit any personal information"

**Comment by QuinnDamerell** [comment]
Great catches. Thanks!
