### ISSUE TITLE
Community rules JSON parsing causes some subreddits to not be loaded.

### ISSUE THREAD

**Issue by eugeniopacceli** [QuinnDamerell/Baconit#51]
When attempting to access some subreddits, such as /r/relationships, the user is unable to load the subreddit thought baconit and a message of "not found" is shown, but the subreddit exists and is online.

The error happens in public async Task<Subreddit> GetSubredditFromWebByDisplayName(string displayName) at  BaconBackend.Managers.SubredditManager, line 195.

foundSubreddit = await Task.Run(() => JsonConvert.DeserializeObject<Subreddit>(subredditData)); throws

"An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Unexpected end when deserializing object. Path 'community_rules[0]', line 1, position 12303.

If there is a handler for this exception, the program may be safely continued."

This exception makes this message appear to the user:

"Hmmm, That's Not Right
We can't load this subreddit right now, check your Internet connection."
and the subreddit related is not loaded.

and the subreddit is not loaded.

Exemple: /r/relationships

Both in Visual Studio deployment and in a Lumia 640XL running Windows 10 beta.

**Comment by eugeniopacceli** [comment]
The json received from /r/relationships is valid.

https://www.reddit.com/r/relationships/about/.json

**Comment by QuinnDamerell** [comment]
Great catch and fix! Thanks so much!
