### ISSUE TITLE
can't login on any W10 device

### ISSUE THREAD

**Issue by HackZy01** [QuinnDamerell/Baconit#99]
W10M and W10 22H1 don't log in at all

![image](https://github.com/QuinnDamerell/Baconit/assets/77678316/a1da7482-b75e-47e3-a838-b0c857ef8a5e)

**Comment by QuinnDamerell** [comment]
This app is no longer supported, thanks for the bug!

**Comment by mediaexplorer74** [comment]
> This app is no longer supported, thanks for the bug!

No longer supported? Holly shit. What's happened on Discord side?

**Comment by mediaexplorer74** [comment]
> W10M and W10 22H1 don't log in at all
> 
> ...

Hi! No connection? Too bad :( 

What version of Baconit you used? 

Are you developer, too? Did you cheched auth deals, espeshially /Managers/AuthManager.cs?

Maybe,
```
 string tokenRequestString = "https://reddit.com/api/v1/authorize.compact?"
```
obsolete?

Try to fix it:
```
            string tokenRequestString = "https://ssl.reddit.com/api/v1/authorize.compact?"
```       
 and recompile your build :)
 
 Best, 
 [m][e]
